### ISSUE TITLE
navigational instruction "going to <app name>" caught by future tense rule

### ISSUE THREAD

**Issue by Felicious** [Felicious/odoo-vale-linter#4]
**Copy and paste the sentence that the rule is or is not supposed to catch** 
> To see the removal strategy in action, create a :ref:`delivery order <inventory/delivery/one-step>`
for six white shirts, either by going to the :menuselection:`Sales app` and creating a new

**Rule name**
(e.g. "Odoo.FutureTense")

**Expected behavior**
"Going to" is used as a verb here, and it's not a case of future tense.

**Comment by samueljlieber** [comment]
This issue can be fixed by prefixing the impersonal or conjugated verb that expresses a condition or action (_it_ or _is_).
```
  - it will( |\n)be
  - it will
  - it shall
  - is going( |\n)to
  - is about( |\n)to
```
