### ISSUE TITLE
"To check" meaning to select vs verify

### ISSUE THREAD

**Issue by Felicious** [Felicious/odoo-vale-linter#5]
**Copy and paste the sentence that the rule is or is not supposed to catch** 
> To check the on-hand stock at each storage location, navigate to the product form, and click the :guilabel:`On Hand` smart button.

**Rule name**
Odoo.WordList: finding "check" to replace with "select"

**Expected behavior**
The rule is supposed to tell you to use "select" when instructing you to click a checkbox.

"Select the checkbox" instead of "check the box". 

However, it should not flag the word "check" when it's used to mean "to verify"

**Comment by samueljlieber** [comment]
Closing this issue since the Odoo.WordList: finding "check" to replace with "select" rule was removed in v1
